# Generated by Django 4.1.7 on 2023-03-12 23:45

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0006_alter_aboutus_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='consejos/post/')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(max_length=200)),
                ('consejo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.consejos')),
            ],
        ),
    ]
