# Generated by Django 4.1.7 on 2023-03-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('logo', models.ImageField(upload_to='consejos/logos')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('type_consejo', models.CharField(choices=[('Local', 'Consejo Local'), ('Curul', 'Curul Especial')], max_length=5)),
            ],
        ),
    ]
