# Generated by Django 4.1.7 on 2023-03-09 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutus_banner_collaborators_documents_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborators',
            name='consejo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.consejos'),
        ),
    ]
