# Generated by Django 4.1.7 on 2023-03-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_prueba_aboutus_consejo_banner_consejo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
