# Generated by Django 4.1.7 on 2023-03-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_aboutus_user_banner_user_collaborators_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborators',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='collaborators',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='collaborators',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='collaborators',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
