# Generated by Django 4.1.7 on 2023-03-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_name_collaborators_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborators',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='position',
            field=models.CharField(max_length=50),
        ),
    ]
